Modified : 리뷰 반영, ReviewView unit test 작성
wecode-bootcamp-korea/27-2nd-Hines-backend pull request #16
Opened 2021-12-22 11:59 UTC by dbwls314

-리뷰 반영, unit test 수정전
-review unit test 수정 중
-review unit test 수정완료

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [x] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [x] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
-라이브 코드 리뷰 리뷰 반영, login decorator 적용한 review view 수정 및 unit test code 작성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
-login decorator를 적용한 unit test를 작성하는 방법을 알게 되었습니다.

<br />

## :: 기타 질문 및 특이 사항
- product price를 str -> int로 전달하기로 결정했습니다.

-    if not Product.objects.filter(id=product_id):
          return JsonResponse({'message':'INAVID_PRODUCT'}, status=400)
 이경우에서는 원하는 에러 메세지가 나오고,
filter().exists()를 적용하게 되면 아예 에러가 나옵니다...
exists() 존재여부를 확인했을때 DB에 없는 데이터를 확인조차 할 수 없어서 제가 설정한 에러를 반환하지 못하는 걸까요...?

2021-12-22 15:10 UTC, jamessoun93 requested changes

2021-12-22 15:10 UTC, jamessoun93 commented on products/views.py
> +            if not Product.objects.filter(id=product_id):
```suggestion
            if not Product.objects.filter(id=product_id).exists():
```

2021-12-22 15:10 UTC, jamessoun93 commented on products/views.py
> +                return JsonResponse({'message':'INAVID_PRODUCT'}, status=400)
```suggestion
                return JsonResponse({'message':'INVALID_PRODUCT_ID'}, status=400)
```

2021-12-23 01:55 UTC, dbwls314 commented on products/views.py
> +            if not Product.objects.filter(id=product_id):
수정하였습니다!

2021-12-23 01:55 UTC, dbwls314 commented on products/views.py
> +                return JsonResponse({'message':'INAVID_PRODUCT'}, status=400)
수정하였습니다!

2021-12-23 03:09 UTC, merged