Add: 프로덕트 리스트 기능구현
wecode-bootcamp-korea/27-2nd-Hines-backend pull request #2
Opened 2021-12-15 04:44 UTC by Djangowon

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 프로덕트 리스트 기능구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- 프로덕트 리스트 전체 목록 불러오는 기능 구현
- 메인페이지(스토어) 카테고리 안의 서브카테고리 클릭 시 나타나는 product list 불러오는 기능 구현
- front 에서 sub_category_id 받아 해당 id 값의 product 를 created_at 으로 정렬하여 100개씩 product list 전달(default)

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2021-12-15 07:47 UTC, lordmyshepherd requested changes

2021-12-15 07:47 UTC, lordmyshepherd commented on products/views.py
> +                q &=Q(sub_category_id=kwargs['sub_category_id'])
```python
:8000/products/1 (X)
:8000/sub_categories/1/products/ (O)
:8000/products?sub_category_id=1 (O)
```
```suggestion
class ProductListView(View):
    def get(self, request, **kwargs):
        try:
            order_method = request.GET.get('sort_method', 'created_at')
            limit        = int(request.GET.get('limit', 100))
            offset       = int(request.GET.get('offset', 0))

            q= Q()

            if kwargs :
                q &=Q(sub_category_id=kwargs['sub_category_id'])
```

2021-12-15 09:56 UTC, Djangowon commented on products/views.py
> +                q &=Q(sub_category_id=kwargs['sub_category_id'])
수정완료 했습니다!

2021-12-16 02:20 UTC, bigfanoftim reviewed
Good!! 추가로 오늘 Unit Test 세션 이후 Test Code도 작성하셔서 같이 Push 해주세요~

2021-12-16 09:56 UTC, Djangowon commented
Test Code 추가 완료 했습니다!

2021-12-16 10:10 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2021-12-16 10:10 UTC, merged