Add: product_detail 페이지 기능 구현
wecode-bootcamp-korea/27-2nd-Hines-backend pull request #4
Opened 2021-12-15 07:22 UTC by dbwls314

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- product 정보 불러오기, product에 해당하는 여러 이미지 불러오기

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. product detialn 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- get 메소드를 통해, product table과 연관된 image table의 관계성을 다시 생각하게 되었습니다.
- 어제 수업때 배운 git rebase를  통해,  여러 commit들을 한개의 commit으로 관리 할 수 있음을 실제로 적용하게 되었습니다.

<br />

## :: 기타 질문 및 특이 사항
- get 메소드를 통해 받고 싶은 정보를 get(self, request)외에도 다양한 정보를 받아 올 수 있나요?

2021-12-16 02:36 UTC, lordmyshepherd requested changes

2021-12-16 02:36 UTC, lordmyshepherd commented on products/views.py
> +                    ]
상품정보 하나를 요청했을 때 호출되는 엔드포인트 아닌가요?
결과 값을 리스트로 감싸서 반환하는 이유가 무엇인가요?

2021-12-16 02:36 UTC, lordmyshepherd commented on products/views.py
> +            image   = Image.objects.filter(id=product_id)
```suggestion
            product = Product.objects.get(id=product_id)
```

2021-12-16 02:36 UTC, lordmyshepherd commented on products/views.py
> +                            'image_url'           : image[0].url
위의 product 객체만 사용해서 image_url을 가져올 수 있도록 코드를 수정해주세요~
```suggestion
                            'image_url' : product....
```

2021-12-16 02:36 UTC, lordmyshepherd commented
유닛테스트 추가해주세요~

2021-12-16 14:29 UTC, dbwls314 commented on products/views.py
> +                    ]
리스트로 무조건 담아야 하는 줄 알고 작성했었는데, 리뷰 확인후 검색해보니 
딕셔너리가 여러개인 경우에 리스트에 담아줘야 한다는 것을 알게 되었습니다.....

리뷰 감사합니다!

2021-12-16 14:29 UTC, dbwls314 commented on products/views.py
> +                            'image_url'           : image[0].url
적용하였습니다!

2021-12-17 09:39 UTC, lordmyshepherd commented
LGTM 👍🏻

2021-12-17 09:39 UTC, merged