Add: KakaoLoginView 구현, test code 첨부
wecode-bootcamp-korea/27-2nd-Hines-backend pull request #6
Opened 2021-12-16 09:25 UTC by Ted0527

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 소셜로그인 view 구현 및 test code 첨부

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
프론트에서 받아온 access_token을 받아서 카카오 서버에 사용자 정보 요청과 함께 보낸다. 이후, 응답과 함께 돌아온
사용자의 정보에서 필요한 데이터를 저장하고, 생성된 DB의 id 로 jwt 를 적용해 우리의 token 으로 가공한 뒤 프론트에게 보낸다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 프론트에서 post 로 보냈을 때, 항상 body 로만 읽어야 한다고 생각 했는데, headers 에 access_token이 담겨 올수도 있다는 사실을 알게되었다.
- Unit Test 에서 생기는 오류는 작성한 code에서 해결해야 하는 오류이지, exception 으로 처리하면 안된다...
- 파이썬의 requests 라이브러리를 통해 백엔드도 요청을 보내고 받을 수 있다는 것을 알았는데, 프론트와의 통신도 한꺼번에 해결하려다 보니, get 과 post 가 섞이는 일이 많았다. 하지만 UnitTest 를 통해서 서로의 method 가 맞지 않으면 발생하는 에러코드를 확인하고 수정해 나갈 수 있게 되었다.

<br />

## :: 기타 질문 및 특이 사항
-

2021-12-16 10:09 UTC, lordmyshepherd requested changes

2021-12-16 10:09 UTC, lordmyshepherd commented on users/views.py
> +                                    headers={'Authorization' : f'Bearer {kakao_token}'})
보통 이렇게 third party 서버의 응답의 성공/실패 여부를 판단할때에는 status 코드로 비교해야 명확하고 디버깅하기 쉽습니다.

```
class KakaoLoginView(View):
    def post(self, request):
        try:
            kakao_access_token    = request.headers['Authorization']
            kakao_user_api_url    = '<https://kapi.kakao.com/v2/user/me>'
            headers     = {"Authorization": f"Bearer ${kakao_access_token}"}

            response = requests.get(kakao_user_api_url, headers=headers)

            if not response.status_code == 200:
		              return JsonResponse...

            ..

```

2021-12-16 10:09 UTC, lordmyshepherd commented on users/views.py
> +class KakaoLoginView(View):
아래와 같이 Kakao API 관련된 로직은 class로 그룹핑할 수 있습니다.  

그렇게 되면 kakao API 관련된 로직은 하나의 class에서 관리하면 된다는 장점이 있고, 만약에 나중에 kakao api 호출부의 수정일 있을 경우 `KakaoLoginView`를 수정할 필요가 없이 `KakaoAPI` 클래스만 수정하면 됩니다. 

결국 Kakao API를 호출하는 위치에서는 Interface만 알고 사용하면 되고 내부적으로 어떻게 구현되었는지 알 필요가 없습니다.

```python
class KakaoAPI:
    def __init__(self, access_token):
        self.access_token = access_token
        self.user_url     = 'https://kapi.kakao.com/v2/user/me'
				self.map_url      = 

    def get_kakao_user(self):
        headers = {"Authorization": f"Bearer ${self.access_token}"}

        response = requests.get(self.user_url, headers=headers)
    
        if not response.status_code == 200:
	    return
        
        return response.json()

    def get_location():
        return   

class KakaoLoginView(View):
    def post(self, request):
        try:
            kakao_access_token = request.headers['Authorization']
            kakao_user = KakaoAPI(kakao_access_token)

```

2021-12-16 10:09 UTC, lordmyshepherd commented on users/views.py
> +        user_info   = requests.get('https://kapi.kakao.com/v2/user/me',
보통 이렇게 third party 서버의 응답의 성공/실패 여부를 판단할때에는 status 코드로 비교해야 명확하고 디버깅하기 쉽습니다.

```
class KakaoLoginView(View):
    def post(self, request):
        try:
            kakao_access_token    = request.headers['Authorization']
            kakao_user_api_url    = '<https://kapi.kakao.com/v2/user/me>'
            headers     = {"Authorization": f"Bearer ${kakao_access_token}"}

            response = requests.get(kakao_user_api_url, headers=headers)

            if not response.status_code == 200:
		              return JsonResponse...

            ..

```

2021-12-17 09:38 UTC, lordmyshepherd requested changes

2021-12-17 09:38 UTC, lordmyshepherd commented on users/views.py
> +            return JsonResponse({'message':'SUCCESS', 'Authorization' : hines_token}, status=201)
생성 여부와 상관 없이 hines_token 반환해주는 로직이 맞지 않나요?
중복되는 코드가 각각 존재합니다. 중복 제거 부탁드려요~

2021-12-17 09:52 UTC, jamessoun93 requested changes

2021-12-17 09:52 UTC, jamessoun93 commented on users/views.py
> +        return
똑같은 클래스가 왜 두개 작성되어있을까요?

2021-12-17 10:39 UTC, Ted0527 commented on users/views.py
> +        return
리베이스 하면서 섞였나 봅니다 ㅜㅜ 마음이 급하니, 제대로 확인도 못했네요. 죄송합니다!

2021-12-18 01:21 UTC, lordmyshepherd requested changes

2021-12-18 01:21 UTC, lordmyshepherd commented on users/views.py
> +        response = requests.get(self.user_url, headers=headers)
`requests` 모듈을 사용하실 때에는 `timeout` 옵션을 반드시 설정해주셔야 합니다.
그 이유는 timeout option을 추가하지 않으면 서버의 응답을 계속해서 기다리고 있는 문제가 발생 합니다. timeout 옵션을 추가해 주세요.

2021-12-18 01:21 UTC, lordmyshepherd commented on users/views.py
> +            )
이미 유저가 존재하는 경우가 고려되지 않은 것 같습니다.

2021-12-18 12:16 UTC, Ted0527 commented on users/views.py
> +        response = requests.get(self.user_url, headers=headers)
timeout option 추가하였고, try catch 로 timeout exception 을 잡아주면서 그에 대한 에러메세지를 응답하도록 설정했습니다.

2021-12-18 12:17 UTC, Ted0527 commented on users/views.py
> +            )
존재하는 유저를 검사하기 위한 조건문을 추가 하였으며, 각각의 상황에 맞게 'CREATED' 와 'SUCCESS' 메세지를 구분하여 응답하도록 설정했습니다.

2021-12-20 02:03 UTC, merged