Add: 프로덕트 리스트 by category 기능추가, 유닛테스트 추가
wecode-bootcamp-korea/27-2nd-Hines-backend pull request #7
Opened 2021-12-17 07:20 UTC by Djangowon

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 프로덕트 리스트 by category 기능추가, 유닛테스트 추가

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- 메뉴 > 카테고리 > 서브카테고리 > 프로덕트 구조
- category_id 를 받아 해당 값에 해당하는 서브카테고리, 프로덕트 리스트 전달 구현
- 유닛테스트 통과

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 

<br />

## :: 기타 질문 및 특이 사항
-

2021-12-17 09:50 UTC, lordmyshepherd requested changes

2021-12-17 09:50 UTC, lordmyshepherd commented on products/views.py
> +        return JsonResponse({'message':'SUCCESS', 'result':categories}, status=200)
카테고리 목록을 반환해주는 엔드포인트를 구현하시려고 하신다면, 아래와 같이 수정과 답변이 필요해 보입니다.

1. (수정 필요) class명 수정 필요 `CategoryView` -> `CategoriesView` 복수로 만들어주세요.
2. (질문) 카테고리 정보를 요청했는데 상품 정보를 반환하는 이유가 있나요? ProductView가 별도로 존재하지 않나요?

2021-12-17 09:51 UTC, lordmyshepherd requested changes

2021-12-17 09:51 UTC, lordmyshepherd commented on products/tests.py
> +        print(response.json())
프린트는 지워주세요.

2021-12-17 09:51 UTC, lordmyshepherd commented on products/tests.py
> +    def test_success_category_view(self):
실패 케이스에 대한 테스트 코드도 추가해주세요~

2021-12-17 10:55 UTC, Djangowon commented on products/views.py
> +        return JsonResponse({'message':'SUCCESS', 'result':categories}, status=200)
ProductListView 가 메뉴 안의 카테고리 안의 서브카테고리를 클릭하면 해당 서브카테고리의 프로덕트를 반환하도록 구현했는데, 서브카테고리가 참조하고 있는 카테고리만 클릭해도 카테고리의 전체 프로덕트 리스트 반환이 필요해서 카테고리 뷰를 새로 만들었습니다. 따로 만들지 않아도 되는 건지 궁금합니다!

2021-12-18 01:17 UTC, lordmyshepherd commented on products/views.py
> +        return JsonResponse({'message':'SUCCESS', 'result':categories}, status=200)
이미 ProductListView에서 반환하고 있는 상품 정보랑 코드가 굉장히 비슷합니다.
CategoriesView는 카테고리 정보만 반환하도록 만들고, ProductListView를 통해서 상품 정보를 받아올 수 있도록 수정해주시면 될 것 같습니다!

2021-12-18 03:53 UTC, Djangowon commented on products/views.py
> +        return JsonResponse({'message':'SUCCESS', 'result':categories}, status=200)
카테고리 정보만 반환하도록 수정하였습니다. 감사합니다!

2021-12-20 02:04 UTC, merged