Add : review 기능구현
wecode-bootcamp-korea/27-2nd-Hines-backend pull request #8
Opened 2021-12-17 08:23 UTC by dbwls314

-review 기초 기능 구현
-추후 로그인 데코레이터 예상하고 작성

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [x] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 로그인 유저만 리뷰 작성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 리뷰를 작성할때 필요한 정보(user id, 리뷰하고 싶은 product id, 리뷰내용, 이미지 여부 상관 없음)으로 리뷰를 등록 기능을 구현하였습니다.
2. 로그인을 안한 유저가 리뷰를 작성하게 될 경우에 대한 에러와 등록되지 않은 product의 id값을 받았을 경우에 대한 에러를 작성하였습니다.  

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 리뷰를 작성할때 필요한 정보와 어떤 상황에서 리뷰를 작성하지 못하는 에러 상황이 있을지 거꾸로 생각하게 되었습니다

<br />

## :: 기타 질문 및 특이 사항
- 현재 erd 구조상, Review table에서 product가 Product 테이블을 참조 하고 있는데, 이 관계로는 로그인한 유저가 구매하지 않은 product도 리뷰를 작성할 수 있다고 생각을 하게 되었습니다.
 만약 유저가 구매한 producrt에 대한 리뷰만 작성할 수 있게 한다면, 
현재의 모델링을 Review 테이블의 product의 참조하는 관계를 Product에서 OderItem으로 수정을 해야해하는 건지, 
아니면 현재이 모델링 수정없이 로직을 작성하는 과정에서 조건문만으로도 작성이 가능한지 궁금합니다...

2021-12-17 09:46 UTC, lordmyshepherd requested changes

2021-12-17 09:46 UTC, lordmyshepherd commented on products/views.py
> +class ReviewView(View):
테스트 코드는 작성이 안되어 있는 것 같아 보입니다!

2021-12-17 09:46 UTC, lordmyshepherd commented on products/views.py
> +	#@decorator # -> 추후 로그인 데코레이터 추가될 예정입니다
decorater가 아직 구현 안된 경우에는 merge 되기까지 기다리는 것이 원칙이지만, 
주말간 작업하실 수 있을 것 같아서 아래와 같이 TODO를 사용해서 표시해주세요.
```suggestion
# TODO : Add login_required decorator
```

2021-12-21 05:20 UTC, jamessoun93 requested changes

2021-12-21 05:20 UTC, jamessoun93 commented on products/urls.py
> +>>>>>>> 9f73f6e (Add : review view 기능구현)
이 부분 확인해주세요.

2021-12-21 05:49 UTC, jamessoun93 approved these changes

2021-12-21 05:49 UTC, merged